### ISSUE TITLE
[FEATURE] Unit test for swift module

### ISSUE THREAD

**Issue by BECATRUE** [snu-quiqcl/swift#107]
### Feature you want to implement
I want to implement the unit test for `swift.swift` module.

#### Test for `parse()`
- TBD

#### Test for `strinfo()`
- TBD

#### Test for `Swift` class
- TBD

#### Test for `_add_to_path()`
- If it doesn't change `sys`.

#### Test for `_get_argparser()`
- If the parser can parse command line arguments.

#### Test for `_read_setup_file()`
- If a setup file is opened well.
- If `app_infos` and `bus_infos` are assigned using the setup file.

#### Test for `main()`
- If each statements is run well.

### Additional context
It is necessary to use `mock` module.

See also: [mock](https://docs.python.org/ko/3/library/unittest.mock.html#module-unittest.mock)

**Comment by BECATRUE** [comment]
I will fill specific todo-lists later.

**Comment by kangz12345** [comment]
I think for unit testing, you don't have to write all the plan.
The test code itself would tell us explicitly.
I guess...?
