### ISSUE TITLE
[FEATURE] System request protocol (swift-call)

### ISSUE THREAD

**Issue by kangz12345** [snu-quiqcl/swift#119]
### Feature you want to implement
Providing a way to call system features for apps.
The targeted features in this issue are:
- create an app
- destroy an app

### How the feature is implemented
I come up with two strategies:
1. ~~Reserve a special channel name, e.g. "swift", and handling the messages broadcast to that channel.~~
2. Add a new dedicated signal in `BaseApp`.

We decided to go with the second option because it is not necessary for the other apps to hear the system requests.

**Comment by kangz12345** [comment]
I think the option 1 is better since it seems more general, e.g., the other apps can also _hear_ that an app is requesting a special operation to swift system.

**Comment by BECATRUE** [comment]
> I think the option 1 is better since it seems more general, e.g., the other apps can also _hear_ that an app is requesting a special operation to swift system.

I agree with you.

I will implement this functions according to your suggestion.

**Comment by kangz12345** [comment]
Please check this before you implement further! @BECATRUE
