### ISSUE TITLE
[TEST] Testing for updated parts

### ISSUE THREAD

**Issue by BECATRUE** [snu-quiqcl/swift#144]
### Feature you want to implement
After all issues, we need to test for updated parts. This is the last order.

**Comment by BECATRUE** [comment]
I have a suggestion!

In the current structure, there is `test` directory, and in this directory, there is only one file `test_swift.py`.
But, in the previous issue, we remove `swift` directory and remain only one file `swift.py`.
Then, how about removing `test` directory, and rename `test_swift.py` to `test.py`?

**Comment by BECATRUE** [comment]
> I have a suggestion!
> 
> In the current structure, there is `test` directory, and in this directory, there is only one file `test_swift.py`. But, in the previous issue, we remove `swift` directory and remain only one file `swift.py`. Then, how about removing `test` directory, and rename `test_swift.py` to `test.py`?

In `test_swift.py`, the meaning of `swift` is the name of `swift` package, but it doesn't exist now.

**Comment by kangz12345** [comment]
I agree with you. Please do that in this PR!
