### ISSUE TITLE
[FEATURE] Add more information to setup.py

### ISSUE THREAD

**Issue by BECATRUE** [snu-quiqcl/swift#145]
### Feature you want to implement
To release our project, we need to add more information for users (may be us).
The `setup.py` of [ARTIQ](https://github.com/m-labs/artiq/blob/master/setup.py) is a good example!

### How the feature is implemented
We can add the develop information, license, etc., but I think _console_scripts_ is the most significant property.
It can make us run `swift` not using `python -m swift.swift` but just `swift` (the command name is an example).

**Comment by kangz12345** [comment]
😮 looks cool!

**Comment by BECATRUE** [comment]
Since we can add various arguments in setup.py, I want to be comfirmed first.
For details, see [setup docs](https://docs.python.org/3/distutils/setupscript.html).

- name: "swift" (already exists)
- version: "_current version_" for example, 1.0.0 (already exists)
- author: "QuIQCL"
- author_email: "_I don't know.._"
- url: "https://sites.google.com/view/quantumcomputingatsnu/home"
- description: "SNU widget integration framework for PyQt"
- long_description: "
A framework for integration of PyQt widgets where they can communicate with each other.
This project is mainly developed for trapped ion experiment controller GUI in SNU QuIQCL.
"
- download_url: "_release url_"
- license: "MIT license"
- install_requires = ["pyqt5"] (already exists)
- packages = find_packages(include=['swift', 'swift.*']) (already exists)

And also, I want to add console script as follows:
```console
python -m swift.swift -s $(setup_path)
swift -s $(setup_path)  // the same result
```

**Comment by BECATRUE** [comment]
Please leave your opinions! @kangz12345

**Comment by kangz12345** [comment]
You can use my e-mail address: kangz12345@snu.ac.kr
`url`: this GitHub page would be good enough.
`package`: it excludes the `examples`, `tests`, etc., right?

**Comment by BECATRUE** [comment]
> You can use my e-mail address: [kangz12345@snu.ac.kr](mailto:kangz12345@snu.ac.kr) `url`: this GitHub page would be good enough. `package`: it excludes the `examples`, `tests`, etc., right?

In terms of `package`, you are right! It includes only `swift` directory, not github root directory.
