### ISSUE TITLE
Merge `swift` and `app` modules and make `swift` as a flat module, not a package

### ISSUE THREAD

**Issue by kangz12345** [snu-quiqcl/swift#153]
I found that the two modules, `swift` and `app`, are in fact dependent to each other.
That implies that they should be in a single module, or we separated something not properly.
I realized this because of a pylint warning `cyclic-import`.
As far as I understand, a module is an independent group of codes and dependences should be acyclic.

For example, in `swift` module, a `Swift` instance manages several `BaseApp` instances where `BaseApp` is defined in `app` module.
However, in `app` module, it uses some functions and classes in `swift` module.
I think it would be better to put them together in a single module.

How do you think of this? @BECATRUE

**Comment by BECATRUE** [comment]
Umm.. You've got a point! 

In the early stages of development, there are a few dependence between two modules. 
But as we develop, there are many calls between them.

So, I agree with your opinion.

**Comment by BECATRUE** [comment]
And also, how about changing the project name `swift`?
As we changed the visibility of this repository into public, I'm worried that the name overlaps with the existing project because this is an official project of QuIQCL..

**Comment by kangz12345** [comment]
I will apply this with #151.

**Comment by kangz12345** [comment]
This will be implemented independently and along with converting a package to a flat module.
