### ISSUE TITLE
[FEATURE] Using QMdiArea

### ISSUE THREAD

**Issue by Ahrrri** [snu-quiqcl/swift#79]
### Feature you want to implement
More flexible placement and resizing of widgets

### How the feature is implemented
Using QMdiArea(Multiple documents interface)

### Additional context
You can move or resize the window of each app freely.
![image](https://user-images.githubusercontent.com/75469641/224691796-6c2e37b7-3677-4ae9-a7ba-a7a31ee89649.png)

This deals with #57.

**Comment by Ahrrri** [comment]
How about this?
@kangz12345 @BECATRUE 
It seems to add some features like auto-resize(like a magnet) or whatever.

**Comment by kangz12345** [comment]
Wow, it looks cool 😮
Could you attach helpful reference links?

**Comment by BECATRUE** [comment]
> Wow, it looks cool 😮 Could you attach helpful reference links?
> 
> * I mentioned the discussion about the layout enhancement.

It looks good, too!

**Comment by Ahrrri** [comment]
I found an attractive option while retaining QDockWidgets.
