### ISSUE TITLE
[FEATURE] Update a part adding/removing DBs

### ISSUE THREAD

**Issue by BECATRUE** [snu-quiqcl/swift#82]
![image](https://user-images.githubusercontent.com/76851886/224932060-067274e9-18a9-494d-96ab-2b9ee7751e34.png)

In the above logging messages, pay attention to messages of which timestamp is 16:50:49.

There are many duplicated messages, such as "Polled database is not selected.".
I just removed a dataset 'A.sqlite' in dbmgr, but it occured duplicated messages.

This occurs because each update calls the function below.
> self.viewerFrame.dbBox.clear()
> self.viewerFrame.dbBox.addItem("")

Other than this, there are several problems such that we always replace all database list to received list, and it is so inefficient.

Therefore, I want to implement as below:
- Remove duplicated messages.
- Not replacing all database list, only adding or removing changed databases.

_Originally posted by @BECATRUE in https://github.com/snu-quiqcl/swift/issues/81#issuecomment-1467311437_

**Comment by kangz12345** [comment]
Please provide more information about the bug. What is the problem and how are you going to fix it?

**Comment by BECATRUE** [comment]
> Please provide more information about the bug. What is the problem and how are you going to fix it?

I will write more infos later.

**Comment by BECATRUE** [comment]
I updated `updateDB()` in `poller`.

Please check it! @kangz12345

**Comment by kangz12345** [comment]
> I updated `updateDB()` in `poller`.
> 
> Please check it! @kangz12345

Do you mean in the commit `eda90e2` in branch `BECATRUE/82/update_db`?

**Comment by BECATRUE** [comment]
> > I updated `updateDB()` in `poller`.
> > Please check it! @kangz12345
> 
> Do you mean in the commit `eda90e2` in branch `BECATRUE/82/update_db`?

Yes, it is right!
