### ISSUE TITLE
Python version choice

### ISSUE THREAD

**Issue by kangz12345** [snu-quiqcl/swift#84]
> First of all, what do you think of updating Python version to 3.11?

Hmm, it's really tempting to do so, but at the same time, I am worried about potential bugs, since Python 3.11 is quite new.

[Status of Python Versions](https://devguide.python.org/versions/) would be helpful reference to decide this.

[Python 3.10](https://peps.python.org/pep-0619/) seems stable enough (in terms of bugs) since the bugfix release schedule is almost ended.

I am not familiar to such version stability issues, so we have to search for good references about this.

_Originally posted by @kangz12345 in https://github.com/snu-quiqcl/swift/issues/80#issuecomment-1467353805_

**Comment by BECATRUE** [comment]
> Since the lab computer uses Python 3.7, how about adding 3.7 runner? @Ahrrri @BECATRUE

Oh, I'm sorry to check this issue lately..

For compatability with lab computer, adding 3.7 runner looks necessary!
Please add it into `Pylint.yml`.

**Comment by BECATRUE** [comment]
About unittest action, I will add 3.7 runner.
