### ISSUE TITLE
[BUG] How to exit mainWindow

### ISSUE THREAD

**Issue by Ahrrri** [snu-quiqcl/swift#86]
### Describe the bug
I usually exit the `mainWindow` by just clicking the X button, but I see some warning/error message every time:
`QThread: Destroyed while thread is still running`

### Expected behavior
It should terminate without any message.

### To Reproduce
1. Execute our swift program as usual.
2. Just click the X button to exit the program.

### Expected causes and correction methods
Maybe we should stop all the active threads before terminating them?

### Screenshots
![image](https://user-images.githubusercontent.com/75469641/225297890-fd0cd2eb-ce85-4df8-a9ba-5339660c24a6.png)

**Comment by BECATRUE** [comment]
I think it is because `Bus`es do not stop immediately (It relies on `timeout` argument).

Like your idea, It is better not to show any message when X button is clicked!

**Comment by kangz12345** [comment]
Since I implemented `Bus`, I will investigate this issue.
Thank you for reporting!
