### ISSUE TITLE
[FEATURE] Initial setting for unit test

### ISSUE THREAD

**Issue by BECATRUE** [snu-quiqcl/swift#88]
First of all, see also: #83 

### Feature you want to implement
I want to initiate the unit test for checking completeness.
- Organize unit test system.
- Test for `swift.app` for checking if the unit test runs well.

#### Test files location
- In the repository, make a directory name `tests`.
- In `tests` directory, there are testing files, e.g. `test_swift.py` and `test_apps.py`.
- In each file, there are several classes which are subclasses of `unittest.TestCase`.

#### Test for `swift.app`
- If `frames()` returns an iterable object.
- If constructor arguments are assigned well.

### Additional context
See also: [unittest](https://docs.python.org/3/library/unittest.html), [coverage](https://coverage.readthedocs.io/en/7.2.2/)

**Comment by kangz12345** [comment]
How are you going to make the unit test system?
For example, to create a new directory `test` or to add a GitHub action, etc.

**Comment by BECATRUE** [comment]
> How are you going to make the unit test system? For example, to create a new directory `test` or to add a GitHub action, etc.

I updated the descriptions.

My focus is to apply unit test to PyQt system rather than systematizing testing, so why don't we talk about the details later?

**Comment by kangz12345** [comment]
> My focus is to apply unit test to PyQt system rather than systematizing testing, so why don't we talk about the details later?

Good idea, then let's discuss the testing system first, and then come back to here.
I think #90 should be closed until we decide the how we test the package.

**Comment by BECATRUE** [comment]
Okay! I closed #90 and let's discuss it.

**Comment by BECATRUE** [comment]
I updated the description. Plz check it! @kangz12345
